apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc2
  template:
    metadata:
      labels:
        app: svc2
    spec:
      containers:
        - name: nginx
          image: ghcr.io/ericmelz/ghcr_test/svc2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc2
spec:
  selector:
    app: svc2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
