name: Build and Push to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write   # Required for pushing to GHCR
      contents: read    # Required for repo access
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build, tag and push Docker images
        run: |
          for service in svc1 svc2 svc3;
              echo "Building and tagging $service..."
              docker build -t ghcr.io/${{ github.repository }}/$service:latest services/$service
              IMAGE_ID=$(docker images -q ghcr.io/ericmelz/ghcr_test/$service:latest)
              docker tag $IMAGE_ID ghcr.io/ericmelz/ghcr_test/$service:latest
              docker tag $IMAGE_ID ghcr.io/ericmelz/ghcr_test/$service:${{ github.sha }}

              echo "Pushing $service..."
              docker push ghcr.io/${{ github.repository }}/$service:latest
              docker push ghcr.io/${{ github.repository }}/$service:${{ github.sha }}
